//
// LICENSE: MIT
//

#ifndef LOX_SRCS_LOX_BACKEND_VIRTUAL_MACHINE_COMMON_ERR_CODE_H_
#define LOX_SRCS_LOX_BACKEND_VIRTUAL_MACHINE_COMMON_ERR_CODE_H_
namespace lox {
enum class ErrCode { NO_ERROR, PARSE_FAIL, INTERPRET_COMPILE_ERROR, INTERPRET_RUNTIME_ERROR };
}  // namespace lox
#endif  // LOX_SRCS_LOX_BACKEND_VIRTUAL_MACHINE_COMMON_ERR_CODE_H_
